// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	model "backend/internal/domain/model"
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockOrderRepository is an autogenerated mock type for the OrderRepository type
type MockOrderRepository struct {
	mock.Mock
}

type MockOrderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderRepository) EXPECT() *MockOrderRepository_Expecter {
	return &MockOrderRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, order
func (_m *MockOrderRepository) Create(ctx context.Context, order *model.Order) error {
	ret := _m.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Order) error); ok {
		r0 = rf(ctx, order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrderRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockOrderRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - order *model.Order
func (_e *MockOrderRepository_Expecter) Create(ctx interface{}, order interface{}) *MockOrderRepository_Create_Call {
	return &MockOrderRepository_Create_Call{Call: _e.mock.On("Create", ctx, order)}
}

func (_c *MockOrderRepository_Create_Call) Run(run func(ctx context.Context, order *model.Order)) *MockOrderRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Order))
	})
	return _c
}

func (_c *MockOrderRepository_Create_Call) Return(_a0 error) *MockOrderRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrderRepository_Create_Call) RunAndReturn(run func(context.Context, *model.Order) error) *MockOrderRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockOrderRepository) Get(ctx context.Context, id uuid.UUID) (*model.Order, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.Order, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.Order); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockOrderRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockOrderRepository_Expecter) Get(ctx interface{}, id interface{}) *MockOrderRepository_Get_Call {
	return &MockOrderRepository_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockOrderRepository_Get_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockOrderRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockOrderRepository_Get_Call) Return(_a0 *model.Order, _a1 error) *MockOrderRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderRepository_Get_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*model.Order, error)) *MockOrderRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// ListByLocationID provides a mock function with given fields: ctx, locationID, limit, offset
func (_m *MockOrderRepository) ListByLocationID(ctx context.Context, locationID uuid.UUID, limit int, offset int) ([]*model.Order, error) {
	ret := _m.Called(ctx, locationID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListByLocationID")
	}

	var r0 []*model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) ([]*model.Order, error)); ok {
		return rf(ctx, locationID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) []*model.Order); ok {
		r0 = rf(ctx, locationID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) error); ok {
		r1 = rf(ctx, locationID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderRepository_ListByLocationID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByLocationID'
type MockOrderRepository_ListByLocationID_Call struct {
	*mock.Call
}

// ListByLocationID is a helper method to define mock.On call
//   - ctx context.Context
//   - locationID uuid.UUID
//   - limit int
//   - offset int
func (_e *MockOrderRepository_Expecter) ListByLocationID(ctx interface{}, locationID interface{}, limit interface{}, offset interface{}) *MockOrderRepository_ListByLocationID_Call {
	return &MockOrderRepository_ListByLocationID_Call{Call: _e.mock.On("ListByLocationID", ctx, locationID, limit, offset)}
}

func (_c *MockOrderRepository_ListByLocationID_Call) Run(run func(ctx context.Context, locationID uuid.UUID, limit int, offset int)) *MockOrderRepository_ListByLocationID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockOrderRepository_ListByLocationID_Call) Return(_a0 []*model.Order, _a1 error) *MockOrderRepository_ListByLocationID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderRepository_ListByLocationID_Call) RunAndReturn(run func(context.Context, uuid.UUID, int, int) ([]*model.Order, error)) *MockOrderRepository_ListByLocationID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByStatus provides a mock function with given fields: ctx, status, limit, offset
func (_m *MockOrderRepository) ListByStatus(ctx context.Context, status model.OrderStatus, limit int, offset int) ([]*model.Order, error) {
	ret := _m.Called(ctx, status, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListByStatus")
	}

	var r0 []*model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.OrderStatus, int, int) ([]*model.Order, error)); ok {
		return rf(ctx, status, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.OrderStatus, int, int) []*model.Order); ok {
		r0 = rf(ctx, status, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.OrderStatus, int, int) error); ok {
		r1 = rf(ctx, status, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderRepository_ListByStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByStatus'
type MockOrderRepository_ListByStatus_Call struct {
	*mock.Call
}

// ListByStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - status model.OrderStatus
//   - limit int
//   - offset int
func (_e *MockOrderRepository_Expecter) ListByStatus(ctx interface{}, status interface{}, limit interface{}, offset interface{}) *MockOrderRepository_ListByStatus_Call {
	return &MockOrderRepository_ListByStatus_Call{Call: _e.mock.On("ListByStatus", ctx, status, limit, offset)}
}

func (_c *MockOrderRepository_ListByStatus_Call) Run(run func(ctx context.Context, status model.OrderStatus, limit int, offset int)) *MockOrderRepository_ListByStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.OrderStatus), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockOrderRepository_ListByStatus_Call) Return(_a0 []*model.Order, _a1 error) *MockOrderRepository_ListByStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderRepository_ListByStatus_Call) RunAndReturn(run func(context.Context, model.OrderStatus, int, int) ([]*model.Order, error)) *MockOrderRepository_ListByStatus_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, order
func (_m *MockOrderRepository) Update(ctx context.Context, order *model.Order) error {
	ret := _m.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Order) error); ok {
		r0 = rf(ctx, order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrderRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockOrderRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - order *model.Order
func (_e *MockOrderRepository_Expecter) Update(ctx interface{}, order interface{}) *MockOrderRepository_Update_Call {
	return &MockOrderRepository_Update_Call{Call: _e.mock.On("Update", ctx, order)}
}

func (_c *MockOrderRepository_Update_Call) Run(run func(ctx context.Context, order *model.Order)) *MockOrderRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Order))
	})
	return _c
}

func (_c *MockOrderRepository_Update_Call) Return(_a0 error) *MockOrderRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrderRepository_Update_Call) RunAndReturn(run func(context.Context, *model.Order) error) *MockOrderRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrderRepository creates a new instance of MockOrderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderRepository {
	mock := &MockOrderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
