// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	model "backend/internal/domain/model"
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockLocationItemRepository is an autogenerated mock type for the LocationItemRepository type
type MockLocationItemRepository struct {
	mock.Mock
}

type MockLocationItemRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLocationItemRepository) EXPECT() *MockLocationItemRepository_Expecter {
	return &MockLocationItemRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, locationItem
func (_m *MockLocationItemRepository) Create(ctx context.Context, locationItem *model.LocationItem) error {
	ret := _m.Called(ctx, locationItem)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.LocationItem) error); ok {
		r0 = rf(ctx, locationItem)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLocationItemRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockLocationItemRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - locationItem *model.LocationItem
func (_e *MockLocationItemRepository_Expecter) Create(ctx interface{}, locationItem interface{}) *MockLocationItemRepository_Create_Call {
	return &MockLocationItemRepository_Create_Call{Call: _e.mock.On("Create", ctx, locationItem)}
}

func (_c *MockLocationItemRepository_Create_Call) Run(run func(ctx context.Context, locationItem *model.LocationItem)) *MockLocationItemRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.LocationItem))
	})
	return _c
}

func (_c *MockLocationItemRepository_Create_Call) Return(_a0 error) *MockLocationItemRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLocationItemRepository_Create_Call) RunAndReturn(run func(context.Context, *model.LocationItem) error) *MockLocationItemRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByItemID provides a mock function with given fields: ctx, itemID
func (_m *MockLocationItemRepository) DeleteByItemID(ctx context.Context, itemID uuid.UUID) error {
	ret := _m.Called(ctx, itemID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByItemID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, itemID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLocationItemRepository_DeleteByItemID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByItemID'
type MockLocationItemRepository_DeleteByItemID_Call struct {
	*mock.Call
}

// DeleteByItemID is a helper method to define mock.On call
//   - ctx context.Context
//   - itemID uuid.UUID
func (_e *MockLocationItemRepository_Expecter) DeleteByItemID(ctx interface{}, itemID interface{}) *MockLocationItemRepository_DeleteByItemID_Call {
	return &MockLocationItemRepository_DeleteByItemID_Call{Call: _e.mock.On("DeleteByItemID", ctx, itemID)}
}

func (_c *MockLocationItemRepository_DeleteByItemID_Call) Run(run func(ctx context.Context, itemID uuid.UUID)) *MockLocationItemRepository_DeleteByItemID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockLocationItemRepository_DeleteByItemID_Call) Return(_a0 error) *MockLocationItemRepository_DeleteByItemID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLocationItemRepository_DeleteByItemID_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockLocationItemRepository_DeleteByItemID_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByLocationID provides a mock function with given fields: ctx, locationID
func (_m *MockLocationItemRepository) DeleteByLocationID(ctx context.Context, locationID uuid.UUID) error {
	ret := _m.Called(ctx, locationID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByLocationID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, locationID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLocationItemRepository_DeleteByLocationID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByLocationID'
type MockLocationItemRepository_DeleteByLocationID_Call struct {
	*mock.Call
}

// DeleteByLocationID is a helper method to define mock.On call
//   - ctx context.Context
//   - locationID uuid.UUID
func (_e *MockLocationItemRepository_Expecter) DeleteByLocationID(ctx interface{}, locationID interface{}) *MockLocationItemRepository_DeleteByLocationID_Call {
	return &MockLocationItemRepository_DeleteByLocationID_Call{Call: _e.mock.On("DeleteByLocationID", ctx, locationID)}
}

func (_c *MockLocationItemRepository_DeleteByLocationID_Call) Run(run func(ctx context.Context, locationID uuid.UUID)) *MockLocationItemRepository_DeleteByLocationID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockLocationItemRepository_DeleteByLocationID_Call) Return(_a0 error) *MockLocationItemRepository_DeleteByLocationID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLocationItemRepository_DeleteByLocationID_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockLocationItemRepository_DeleteByLocationID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockLocationItemRepository) GetByID(ctx context.Context, id uuid.UUID) (*model.LocationItem, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.LocationItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.LocationItem, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.LocationItem); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.LocationItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLocationItemRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockLocationItemRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockLocationItemRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockLocationItemRepository_GetByID_Call {
	return &MockLocationItemRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockLocationItemRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockLocationItemRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockLocationItemRepository_GetByID_Call) Return(_a0 *model.LocationItem, _a1 error) *MockLocationItemRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLocationItemRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*model.LocationItem, error)) *MockLocationItemRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByLocationAndItem provides a mock function with given fields: ctx, locationID, itemID
func (_m *MockLocationItemRepository) GetByLocationAndItem(ctx context.Context, locationID uuid.UUID, itemID uuid.UUID) (*model.LocationItem, error) {
	ret := _m.Called(ctx, locationID, itemID)

	if len(ret) == 0 {
		panic("no return value specified for GetByLocationAndItem")
	}

	var r0 *model.LocationItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*model.LocationItem, error)); ok {
		return rf(ctx, locationID, itemID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *model.LocationItem); ok {
		r0 = rf(ctx, locationID, itemID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.LocationItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, locationID, itemID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLocationItemRepository_GetByLocationAndItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByLocationAndItem'
type MockLocationItemRepository_GetByLocationAndItem_Call struct {
	*mock.Call
}

// GetByLocationAndItem is a helper method to define mock.On call
//   - ctx context.Context
//   - locationID uuid.UUID
//   - itemID uuid.UUID
func (_e *MockLocationItemRepository_Expecter) GetByLocationAndItem(ctx interface{}, locationID interface{}, itemID interface{}) *MockLocationItemRepository_GetByLocationAndItem_Call {
	return &MockLocationItemRepository_GetByLocationAndItem_Call{Call: _e.mock.On("GetByLocationAndItem", ctx, locationID, itemID)}
}

func (_c *MockLocationItemRepository_GetByLocationAndItem_Call) Run(run func(ctx context.Context, locationID uuid.UUID, itemID uuid.UUID)) *MockLocationItemRepository_GetByLocationAndItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockLocationItemRepository_GetByLocationAndItem_Call) Return(_a0 *model.LocationItem, _a1 error) *MockLocationItemRepository_GetByLocationAndItem_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLocationItemRepository_GetByLocationAndItem_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*model.LocationItem, error)) *MockLocationItemRepository_GetByLocationAndItem_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, locationID, limit, offset
func (_m *MockLocationItemRepository) List(ctx context.Context, locationID uuid.UUID, limit int, offset int) ([]*model.LocationItem, error) {
	ret := _m.Called(ctx, locationID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*model.LocationItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) ([]*model.LocationItem, error)); ok {
		return rf(ctx, locationID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) []*model.LocationItem); ok {
		r0 = rf(ctx, locationID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.LocationItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) error); ok {
		r1 = rf(ctx, locationID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLocationItemRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockLocationItemRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - locationID uuid.UUID
//   - limit int
//   - offset int
func (_e *MockLocationItemRepository_Expecter) List(ctx interface{}, locationID interface{}, limit interface{}, offset interface{}) *MockLocationItemRepository_List_Call {
	return &MockLocationItemRepository_List_Call{Call: _e.mock.On("List", ctx, locationID, limit, offset)}
}

func (_c *MockLocationItemRepository_List_Call) Run(run func(ctx context.Context, locationID uuid.UUID, limit int, offset int)) *MockLocationItemRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockLocationItemRepository_List_Call) Return(_a0 []*model.LocationItem, _a1 error) *MockLocationItemRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLocationItemRepository_List_Call) RunAndReturn(run func(context.Context, uuid.UUID, int, int) ([]*model.LocationItem, error)) *MockLocationItemRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, locationItem
func (_m *MockLocationItemRepository) Update(ctx context.Context, locationItem *model.LocationItem) error {
	ret := _m.Called(ctx, locationItem)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.LocationItem) error); ok {
		r0 = rf(ctx, locationItem)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLocationItemRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockLocationItemRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - locationItem *model.LocationItem
func (_e *MockLocationItemRepository_Expecter) Update(ctx interface{}, locationItem interface{}) *MockLocationItemRepository_Update_Call {
	return &MockLocationItemRepository_Update_Call{Call: _e.mock.On("Update", ctx, locationItem)}
}

func (_c *MockLocationItemRepository_Update_Call) Run(run func(ctx context.Context, locationItem *model.LocationItem)) *MockLocationItemRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.LocationItem))
	})
	return _c
}

func (_c *MockLocationItemRepository_Update_Call) Return(_a0 error) *MockLocationItemRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLocationItemRepository_Update_Call) RunAndReturn(run func(context.Context, *model.LocationItem) error) *MockLocationItemRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLocationItemRepository creates a new instance of MockLocationItemRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLocationItemRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLocationItemRepository {
	mock := &MockLocationItemRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
