// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	model "backend/internal/domain/model"
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockLocationRepository is an autogenerated mock type for the LocationRepository type
type MockLocationRepository struct {
	mock.Mock
}

type MockLocationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLocationRepository) EXPECT() *MockLocationRepository_Expecter {
	return &MockLocationRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, location
func (_m *MockLocationRepository) Create(ctx context.Context, location *model.Location) error {
	ret := _m.Called(ctx, location)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Location) error); ok {
		r0 = rf(ctx, location)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLocationRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockLocationRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - location *model.Location
func (_e *MockLocationRepository_Expecter) Create(ctx interface{}, location interface{}) *MockLocationRepository_Create_Call {
	return &MockLocationRepository_Create_Call{Call: _e.mock.On("Create", ctx, location)}
}

func (_c *MockLocationRepository_Create_Call) Run(run func(ctx context.Context, location *model.Location)) *MockLocationRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Location))
	})
	return _c
}

func (_c *MockLocationRepository_Create_Call) Return(_a0 error) *MockLocationRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLocationRepository_Create_Call) RunAndReturn(run func(context.Context, *model.Location) error) *MockLocationRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockLocationRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLocationRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockLocationRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockLocationRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockLocationRepository_Delete_Call {
	return &MockLocationRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockLocationRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockLocationRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockLocationRepository_Delete_Call) Return(_a0 error) *MockLocationRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLocationRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockLocationRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockLocationRepository) GetByID(ctx context.Context, id uuid.UUID) (*model.Location, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.Location
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.Location, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.Location); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Location)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLocationRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockLocationRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockLocationRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockLocationRepository_GetByID_Call {
	return &MockLocationRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockLocationRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockLocationRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockLocationRepository_GetByID_Call) Return(_a0 *model.Location, _a1 error) *MockLocationRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLocationRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*model.Location, error)) *MockLocationRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetBySlug provides a mock function with given fields: ctx, slug
func (_m *MockLocationRepository) GetBySlug(ctx context.Context, slug string) (*model.Location, error) {
	ret := _m.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for GetBySlug")
	}

	var r0 *model.Location
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Location, error)); ok {
		return rf(ctx, slug)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Location); ok {
		r0 = rf(ctx, slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Location)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLocationRepository_GetBySlug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBySlug'
type MockLocationRepository_GetBySlug_Call struct {
	*mock.Call
}

// GetBySlug is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
func (_e *MockLocationRepository_Expecter) GetBySlug(ctx interface{}, slug interface{}) *MockLocationRepository_GetBySlug_Call {
	return &MockLocationRepository_GetBySlug_Call{Call: _e.mock.On("GetBySlug", ctx, slug)}
}

func (_c *MockLocationRepository_GetBySlug_Call) Run(run func(ctx context.Context, slug string)) *MockLocationRepository_GetBySlug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockLocationRepository_GetBySlug_Call) Return(_a0 *model.Location, _a1 error) *MockLocationRepository_GetBySlug_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLocationRepository_GetBySlug_Call) RunAndReturn(run func(context.Context, string) (*model.Location, error)) *MockLocationRepository_GetBySlug_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx
func (_m *MockLocationRepository) List(ctx context.Context) ([]*model.Location, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*model.Location
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*model.Location, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*model.Location); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Location)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLocationRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockLocationRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockLocationRepository_Expecter) List(ctx interface{}) *MockLocationRepository_List_Call {
	return &MockLocationRepository_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockLocationRepository_List_Call) Run(run func(ctx context.Context)) *MockLocationRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockLocationRepository_List_Call) Return(_a0 []*model.Location, _a1 error) *MockLocationRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLocationRepository_List_Call) RunAndReturn(run func(context.Context) ([]*model.Location, error)) *MockLocationRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, location
func (_m *MockLocationRepository) Update(ctx context.Context, location *model.Location) error {
	ret := _m.Called(ctx, location)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Location) error); ok {
		r0 = rf(ctx, location)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLocationRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockLocationRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - location *model.Location
func (_e *MockLocationRepository_Expecter) Update(ctx interface{}, location interface{}) *MockLocationRepository_Update_Call {
	return &MockLocationRepository_Update_Call{Call: _e.mock.On("Update", ctx, location)}
}

func (_c *MockLocationRepository_Update_Call) Run(run func(ctx context.Context, location *model.Location)) *MockLocationRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Location))
	})
	return _c
}

func (_c *MockLocationRepository_Update_Call) Return(_a0 error) *MockLocationRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLocationRepository_Update_Call) RunAndReturn(run func(context.Context, *model.Location) error) *MockLocationRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLocationRepository creates a new instance of MockLocationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLocationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLocationRepository {
	mock := &MockLocationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
