// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	model "backend/internal/domain/model"
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockTransactionRepository is an autogenerated mock type for the TransactionRepository type
type MockTransactionRepository struct {
	mock.Mock
}

type MockTransactionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactionRepository) EXPECT() *MockTransactionRepository_Expecter {
	return &MockTransactionRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, transaction
func (_m *MockTransactionRepository) Create(ctx context.Context, transaction *model.Transaction) error {
	ret := _m.Called(ctx, transaction)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Transaction) error); ok {
		r0 = rf(ctx, transaction)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransactionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTransactionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - transaction *model.Transaction
func (_e *MockTransactionRepository_Expecter) Create(ctx interface{}, transaction interface{}) *MockTransactionRepository_Create_Call {
	return &MockTransactionRepository_Create_Call{Call: _e.mock.On("Create", ctx, transaction)}
}

func (_c *MockTransactionRepository_Create_Call) Run(run func(ctx context.Context, transaction *model.Transaction)) *MockTransactionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Transaction))
	})
	return _c
}

func (_c *MockTransactionRepository_Create_Call) Return(_a0 error) *MockTransactionRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransactionRepository_Create_Call) RunAndReturn(run func(context.Context, *model.Transaction) error) *MockTransactionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockTransactionRepository) GetByID(ctx context.Context, id uuid.UUID) (*model.Transaction, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.Transaction, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.Transaction); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockTransactionRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockTransactionRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockTransactionRepository_GetByID_Call {
	return &MockTransactionRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockTransactionRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockTransactionRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockTransactionRepository_GetByID_Call) Return(_a0 *model.Transaction, _a1 error) *MockTransactionRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*model.Transaction, error)) *MockTransactionRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetBySbpID provides a mock function with given fields: ctx, sbpID
func (_m *MockTransactionRepository) GetBySbpID(ctx context.Context, sbpID string) (*model.Transaction, error) {
	ret := _m.Called(ctx, sbpID)

	if len(ret) == 0 {
		panic("no return value specified for GetBySbpID")
	}

	var r0 *model.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Transaction, error)); ok {
		return rf(ctx, sbpID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Transaction); ok {
		r0 = rf(ctx, sbpID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, sbpID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionRepository_GetBySbpID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBySbpID'
type MockTransactionRepository_GetBySbpID_Call struct {
	*mock.Call
}

// GetBySbpID is a helper method to define mock.On call
//   - ctx context.Context
//   - sbpID string
func (_e *MockTransactionRepository_Expecter) GetBySbpID(ctx interface{}, sbpID interface{}) *MockTransactionRepository_GetBySbpID_Call {
	return &MockTransactionRepository_GetBySbpID_Call{Call: _e.mock.On("GetBySbpID", ctx, sbpID)}
}

func (_c *MockTransactionRepository_GetBySbpID_Call) Run(run func(ctx context.Context, sbpID string)) *MockTransactionRepository_GetBySbpID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTransactionRepository_GetBySbpID_Call) Return(_a0 *model.Transaction, _a1 error) *MockTransactionRepository_GetBySbpID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionRepository_GetBySbpID_Call) RunAndReturn(run func(context.Context, string) (*model.Transaction, error)) *MockTransactionRepository_GetBySbpID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, orderID
func (_m *MockTransactionRepository) List(ctx context.Context, orderID uuid.UUID) ([]*model.Transaction, error) {
	ret := _m.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*model.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*model.Transaction, error)); ok {
		return rf(ctx, orderID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*model.Transaction); ok {
		r0 = rf(ctx, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockTransactionRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
func (_e *MockTransactionRepository_Expecter) List(ctx interface{}, orderID interface{}) *MockTransactionRepository_List_Call {
	return &MockTransactionRepository_List_Call{Call: _e.mock.On("List", ctx, orderID)}
}

func (_c *MockTransactionRepository_List_Call) Run(run func(ctx context.Context, orderID uuid.UUID)) *MockTransactionRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockTransactionRepository_List_Call) Return(_a0 []*model.Transaction, _a1 error) *MockTransactionRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionRepository_List_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*model.Transaction, error)) *MockTransactionRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, transaction
func (_m *MockTransactionRepository) Update(ctx context.Context, transaction *model.Transaction) error {
	ret := _m.Called(ctx, transaction)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Transaction) error); ok {
		r0 = rf(ctx, transaction)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransactionRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTransactionRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - transaction *model.Transaction
func (_e *MockTransactionRepository_Expecter) Update(ctx interface{}, transaction interface{}) *MockTransactionRepository_Update_Call {
	return &MockTransactionRepository_Update_Call{Call: _e.mock.On("Update", ctx, transaction)}
}

func (_c *MockTransactionRepository_Update_Call) Run(run func(ctx context.Context, transaction *model.Transaction)) *MockTransactionRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Transaction))
	})
	return _c
}

func (_c *MockTransactionRepository_Update_Call) Return(_a0 error) *MockTransactionRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransactionRepository_Update_Call) RunAndReturn(run func(context.Context, *model.Transaction) error) *MockTransactionRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTransactionRepository creates a new instance of MockTransactionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactionRepository {
	mock := &MockTransactionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
