// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	model "backend/internal/domain/model"
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockOrderItemRepository is an autogenerated mock type for the OrderItemRepository type
type MockOrderItemRepository struct {
	mock.Mock
}

type MockOrderItemRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderItemRepository) EXPECT() *MockOrderItemRepository_Expecter {
	return &MockOrderItemRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, orderID, orderItem
func (_m *MockOrderItemRepository) Create(ctx context.Context, orderID uuid.UUID, orderItem *model.OrderItem) error {
	ret := _m.Called(ctx, orderID, orderItem)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *model.OrderItem) error); ok {
		r0 = rf(ctx, orderID, orderItem)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrderItemRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockOrderItemRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
//   - orderItem *model.OrderItem
func (_e *MockOrderItemRepository_Expecter) Create(ctx interface{}, orderID interface{}, orderItem interface{}) *MockOrderItemRepository_Create_Call {
	return &MockOrderItemRepository_Create_Call{Call: _e.mock.On("Create", ctx, orderID, orderItem)}
}

func (_c *MockOrderItemRepository_Create_Call) Run(run func(ctx context.Context, orderID uuid.UUID, orderItem *model.OrderItem)) *MockOrderItemRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*model.OrderItem))
	})
	return _c
}

func (_c *MockOrderItemRepository_Create_Call) Return(_a0 error) *MockOrderItemRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrderItemRepository_Create_Call) RunAndReturn(run func(context.Context, uuid.UUID, *model.OrderItem) error) *MockOrderItemRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateMany provides a mock function with given fields: ctx, orderID, orderItems
func (_m *MockOrderItemRepository) CreateMany(ctx context.Context, orderID uuid.UUID, orderItems []*model.OrderItem) error {
	ret := _m.Called(ctx, orderID, orderItems)

	if len(ret) == 0 {
		panic("no return value specified for CreateMany")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, []*model.OrderItem) error); ok {
		r0 = rf(ctx, orderID, orderItems)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrderItemRepository_CreateMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMany'
type MockOrderItemRepository_CreateMany_Call struct {
	*mock.Call
}

// CreateMany is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
//   - orderItems []*model.OrderItem
func (_e *MockOrderItemRepository_Expecter) CreateMany(ctx interface{}, orderID interface{}, orderItems interface{}) *MockOrderItemRepository_CreateMany_Call {
	return &MockOrderItemRepository_CreateMany_Call{Call: _e.mock.On("CreateMany", ctx, orderID, orderItems)}
}

func (_c *MockOrderItemRepository_CreateMany_Call) Run(run func(ctx context.Context, orderID uuid.UUID, orderItems []*model.OrderItem)) *MockOrderItemRepository_CreateMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].([]*model.OrderItem))
	})
	return _c
}

func (_c *MockOrderItemRepository_CreateMany_Call) Return(_a0 error) *MockOrderItemRepository_CreateMany_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrderItemRepository_CreateMany_Call) RunAndReturn(run func(context.Context, uuid.UUID, []*model.OrderItem) error) *MockOrderItemRepository_CreateMany_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, orderID
func (_m *MockOrderItemRepository) List(ctx context.Context, orderID uuid.UUID) ([]*model.OrderItem, error) {
	ret := _m.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*model.OrderItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*model.OrderItem, error)); ok {
		return rf(ctx, orderID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*model.OrderItem); ok {
		r0 = rf(ctx, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.OrderItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderItemRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockOrderItemRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
func (_e *MockOrderItemRepository_Expecter) List(ctx interface{}, orderID interface{}) *MockOrderItemRepository_List_Call {
	return &MockOrderItemRepository_List_Call{Call: _e.mock.On("List", ctx, orderID)}
}

func (_c *MockOrderItemRepository_List_Call) Run(run func(ctx context.Context, orderID uuid.UUID)) *MockOrderItemRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockOrderItemRepository_List_Call) Return(_a0 []*model.OrderItem, _a1 error) *MockOrderItemRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderItemRepository_List_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*model.OrderItem, error)) *MockOrderItemRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrderItemRepository creates a new instance of MockOrderItemRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderItemRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderItemRepository {
	mock := &MockOrderItemRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
