// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	model "backend/internal/domain/model"
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockAdminRepository is an autogenerated mock type for the AdminRepository type
type MockAdminRepository struct {
	mock.Mock
}

type MockAdminRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAdminRepository) EXPECT() *MockAdminRepository_Expecter {
	return &MockAdminRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, admin
func (_m *MockAdminRepository) Create(ctx context.Context, admin *model.Admin) error {
	ret := _m.Called(ctx, admin)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Admin) error); ok {
		r0 = rf(ctx, admin)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAdminRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAdminRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - admin *model.Admin
func (_e *MockAdminRepository_Expecter) Create(ctx interface{}, admin interface{}) *MockAdminRepository_Create_Call {
	return &MockAdminRepository_Create_Call{Call: _e.mock.On("Create", ctx, admin)}
}

func (_c *MockAdminRepository_Create_Call) Run(run func(ctx context.Context, admin *model.Admin)) *MockAdminRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Admin))
	})
	return _c
}

func (_c *MockAdminRepository_Create_Call) Return(_a0 error) *MockAdminRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAdminRepository_Create_Call) RunAndReturn(run func(context.Context, *model.Admin) error) *MockAdminRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockAdminRepository) GetByID(ctx context.Context, id uuid.UUID) (*model.Admin, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.Admin
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.Admin, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.Admin); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Admin)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdminRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockAdminRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockAdminRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockAdminRepository_GetByID_Call {
	return &MockAdminRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockAdminRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockAdminRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockAdminRepository_GetByID_Call) Return(_a0 *model.Admin, _a1 error) *MockAdminRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdminRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*model.Admin, error)) *MockAdminRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByLogin provides a mock function with given fields: ctx, login
func (_m *MockAdminRepository) GetByLogin(ctx context.Context, login string) (*model.Admin, error) {
	ret := _m.Called(ctx, login)

	if len(ret) == 0 {
		panic("no return value specified for GetByLogin")
	}

	var r0 *model.Admin
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Admin, error)); ok {
		return rf(ctx, login)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Admin); ok {
		r0 = rf(ctx, login)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Admin)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, login)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdminRepository_GetByLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByLogin'
type MockAdminRepository_GetByLogin_Call struct {
	*mock.Call
}

// GetByLogin is a helper method to define mock.On call
//   - ctx context.Context
//   - login string
func (_e *MockAdminRepository_Expecter) GetByLogin(ctx interface{}, login interface{}) *MockAdminRepository_GetByLogin_Call {
	return &MockAdminRepository_GetByLogin_Call{Call: _e.mock.On("GetByLogin", ctx, login)}
}

func (_c *MockAdminRepository_GetByLogin_Call) Run(run func(ctx context.Context, login string)) *MockAdminRepository_GetByLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAdminRepository_GetByLogin_Call) Return(_a0 *model.Admin, _a1 error) *MockAdminRepository_GetByLogin_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdminRepository_GetByLogin_Call) RunAndReturn(run func(context.Context, string) (*model.Admin, error)) *MockAdminRepository_GetByLogin_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function with given fields: ctx, admin
func (_m *MockAdminRepository) Upsert(ctx context.Context, admin *model.Admin) error {
	ret := _m.Called(ctx, admin)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Admin) error); ok {
		r0 = rf(ctx, admin)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAdminRepository_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type MockAdminRepository_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - admin *model.Admin
func (_e *MockAdminRepository_Expecter) Upsert(ctx interface{}, admin interface{}) *MockAdminRepository_Upsert_Call {
	return &MockAdminRepository_Upsert_Call{Call: _e.mock.On("Upsert", ctx, admin)}
}

func (_c *MockAdminRepository_Upsert_Call) Run(run func(ctx context.Context, admin *model.Admin)) *MockAdminRepository_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Admin))
	})
	return _c
}

func (_c *MockAdminRepository_Upsert_Call) Return(_a0 error) *MockAdminRepository_Upsert_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAdminRepository_Upsert_Call) RunAndReturn(run func(context.Context, *model.Admin) error) *MockAdminRepository_Upsert_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAdminRepository creates a new instance of MockAdminRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAdminRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAdminRepository {
	mock := &MockAdminRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
