// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	model "backend/internal/domain/model"
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockItemRepository is an autogenerated mock type for the ItemRepository type
type MockItemRepository struct {
	mock.Mock
}

type MockItemRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockItemRepository) EXPECT() *MockItemRepository_Expecter {
	return &MockItemRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, item
func (_m *MockItemRepository) Create(ctx context.Context, item *model.Item) error {
	ret := _m.Called(ctx, item)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Item) error); ok {
		r0 = rf(ctx, item)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockItemRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockItemRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - item *model.Item
func (_e *MockItemRepository_Expecter) Create(ctx interface{}, item interface{}) *MockItemRepository_Create_Call {
	return &MockItemRepository_Create_Call{Call: _e.mock.On("Create", ctx, item)}
}

func (_c *MockItemRepository_Create_Call) Run(run func(ctx context.Context, item *model.Item)) *MockItemRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Item))
	})
	return _c
}

func (_c *MockItemRepository_Create_Call) Return(_a0 error) *MockItemRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockItemRepository_Create_Call) RunAndReturn(run func(context.Context, *model.Item) error) *MockItemRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockItemRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockItemRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockItemRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockItemRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockItemRepository_Delete_Call {
	return &MockItemRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockItemRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockItemRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockItemRepository_Delete_Call) Return(_a0 error) *MockItemRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockItemRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockItemRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockItemRepository) Get(ctx context.Context, id uuid.UUID) (*model.Item, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.Item, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.Item); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Item)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockItemRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockItemRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockItemRepository_Expecter) Get(ctx interface{}, id interface{}) *MockItemRepository_Get_Call {
	return &MockItemRepository_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockItemRepository_Get_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockItemRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockItemRepository_Get_Call) Return(_a0 *model.Item, _a1 error) *MockItemRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockItemRepository_Get_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*model.Item, error)) *MockItemRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// ListAll provides a mock function with given fields: ctx
func (_m *MockItemRepository) ListAll(ctx context.Context) ([]*model.Item, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListAll")
	}

	var r0 []*model.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*model.Item, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*model.Item); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Item)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockItemRepository_ListAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAll'
type MockItemRepository_ListAll_Call struct {
	*mock.Call
}

// ListAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockItemRepository_Expecter) ListAll(ctx interface{}) *MockItemRepository_ListAll_Call {
	return &MockItemRepository_ListAll_Call{Call: _e.mock.On("ListAll", ctx)}
}

func (_c *MockItemRepository_ListAll_Call) Run(run func(ctx context.Context)) *MockItemRepository_ListAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockItemRepository_ListAll_Call) Return(_a0 []*model.Item, _a1 error) *MockItemRepository_ListAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockItemRepository_ListAll_Call) RunAndReturn(run func(context.Context) ([]*model.Item, error)) *MockItemRepository_ListAll_Call {
	_c.Call.Return(run)
	return _c
}

// ListByIDs provides a mock function with given fields: ctx, ids
func (_m *MockItemRepository) ListByIDs(ctx context.Context, ids []uuid.UUID) ([]*model.Item, error) {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for ListByIDs")
	}

	var r0 []*model.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) ([]*model.Item, error)); ok {
		return rf(ctx, ids)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) []*model.Item); ok {
		r0 = rf(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Item)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []uuid.UUID) error); ok {
		r1 = rf(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockItemRepository_ListByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByIDs'
type MockItemRepository_ListByIDs_Call struct {
	*mock.Call
}

// ListByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []uuid.UUID
func (_e *MockItemRepository_Expecter) ListByIDs(ctx interface{}, ids interface{}) *MockItemRepository_ListByIDs_Call {
	return &MockItemRepository_ListByIDs_Call{Call: _e.mock.On("ListByIDs", ctx, ids)}
}

func (_c *MockItemRepository_ListByIDs_Call) Run(run func(ctx context.Context, ids []uuid.UUID)) *MockItemRepository_ListByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]uuid.UUID))
	})
	return _c
}

func (_c *MockItemRepository_ListByIDs_Call) Return(_a0 []*model.Item, _a1 error) *MockItemRepository_ListByIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockItemRepository_ListByIDs_Call) RunAndReturn(run func(context.Context, []uuid.UUID) ([]*model.Item, error)) *MockItemRepository_ListByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, item
func (_m *MockItemRepository) Update(ctx context.Context, item *model.Item) error {
	ret := _m.Called(ctx, item)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Item) error); ok {
		r0 = rf(ctx, item)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockItemRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockItemRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - item *model.Item
func (_e *MockItemRepository_Expecter) Update(ctx interface{}, item interface{}) *MockItemRepository_Update_Call {
	return &MockItemRepository_Update_Call{Call: _e.mock.On("Update", ctx, item)}
}

func (_c *MockItemRepository_Update_Call) Run(run func(ctx context.Context, item *model.Item)) *MockItemRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Item))
	})
	return _c
}

func (_c *MockItemRepository_Update_Call) Return(_a0 error) *MockItemRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockItemRepository_Update_Call) RunAndReturn(run func(context.Context, *model.Item) error) *MockItemRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockItemRepository creates a new instance of MockItemRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockItemRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockItemRepository {
	mock := &MockItemRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
