// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockQRCodeGenerator is an autogenerated mock type for the QRCodeGenerator type
type MockQRCodeGenerator struct {
	mock.Mock
}

type MockQRCodeGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQRCodeGenerator) EXPECT() *MockQRCodeGenerator_Expecter {
	return &MockQRCodeGenerator_Expecter{mock: &_m.Mock}
}

// Generate provides a mock function with given fields: slug
func (_m *MockQRCodeGenerator) Generate(slug string) ([]byte, error) {
	ret := _m.Called(slug)

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return rf(slug)
	}
	if rf, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = rf(slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(slug)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQRCodeGenerator_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type MockQRCodeGenerator_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
//   - slug string
func (_e *MockQRCodeGenerator_Expecter) Generate(slug interface{}) *MockQRCodeGenerator_Generate_Call {
	return &MockQRCodeGenerator_Generate_Call{Call: _e.mock.On("Generate", slug)}
}

func (_c *MockQRCodeGenerator_Generate_Call) Run(run func(slug string)) *MockQRCodeGenerator_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockQRCodeGenerator_Generate_Call) Return(_a0 []byte, _a1 error) *MockQRCodeGenerator_Generate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQRCodeGenerator_Generate_Call) RunAndReturn(run func(string) ([]byte, error)) *MockQRCodeGenerator_Generate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQRCodeGenerator creates a new instance of MockQRCodeGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQRCodeGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQRCodeGenerator {
	mock := &MockQRCodeGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
