// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockPaymentGateway is an autogenerated mock type for the PaymentGateway type
type MockPaymentGateway struct {
	mock.Mock
}

type MockPaymentGateway_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPaymentGateway) EXPECT() *MockPaymentGateway_Expecter {
	return &MockPaymentGateway_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, amount, returnURL, orderID
func (_m *MockPaymentGateway) Create(ctx context.Context, amount int64, returnURL string, orderID uuid.UUID) (string, string, error) {
	ret := _m.Called(ctx, amount, returnURL, orderID)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 string
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, uuid.UUID) (string, string, error)); ok {
		return rf(ctx, amount, returnURL, orderID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, uuid.UUID) string); ok {
		r0 = rf(ctx, amount, returnURL, orderID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string, uuid.UUID) string); ok {
		r1 = rf(ctx, amount, returnURL, orderID)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int64, string, uuid.UUID) error); ok {
		r2 = rf(ctx, amount, returnURL, orderID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockPaymentGateway_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockPaymentGateway_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - amount int64
//   - returnURL string
//   - orderID uuid.UUID
func (_e *MockPaymentGateway_Expecter) Create(ctx interface{}, amount interface{}, returnURL interface{}, orderID interface{}) *MockPaymentGateway_Create_Call {
	return &MockPaymentGateway_Create_Call{Call: _e.mock.On("Create", ctx, amount, returnURL, orderID)}
}

func (_c *MockPaymentGateway_Create_Call) Run(run func(ctx context.Context, amount int64, returnURL string, orderID uuid.UUID)) *MockPaymentGateway_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string), args[3].(uuid.UUID))
	})
	return _c
}

func (_c *MockPaymentGateway_Create_Call) Return(_a0 string, _a1 string, _a2 error) *MockPaymentGateway_Create_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockPaymentGateway_Create_Call) RunAndReturn(run func(context.Context, int64, string, uuid.UUID) (string, string, error)) *MockPaymentGateway_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetStatus provides a mock function with given fields: ctx, externalID
func (_m *MockPaymentGateway) GetStatus(ctx context.Context, externalID string) (string, error) {
	ret := _m.Called(ctx, externalID)

	if len(ret) == 0 {
		panic("no return value specified for GetStatus")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, externalID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, externalID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, externalID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentGateway_GetStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatus'
type MockPaymentGateway_GetStatus_Call struct {
	*mock.Call
}

// GetStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - externalID string
func (_e *MockPaymentGateway_Expecter) GetStatus(ctx interface{}, externalID interface{}) *MockPaymentGateway_GetStatus_Call {
	return &MockPaymentGateway_GetStatus_Call{Call: _e.mock.On("GetStatus", ctx, externalID)}
}

func (_c *MockPaymentGateway_GetStatus_Call) Run(run func(ctx context.Context, externalID string)) *MockPaymentGateway_GetStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPaymentGateway_GetStatus_Call) Return(_a0 string, _a1 error) *MockPaymentGateway_GetStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentGateway_GetStatus_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockPaymentGateway_GetStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPaymentGateway creates a new instance of MockPaymentGateway. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaymentGateway(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaymentGateway {
	mock := &MockPaymentGateway{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
