basePath: /api/v1
definitions:
  dto.AdminAuthRequest:
    properties:
      login:
        description: Логин администратора (минимум 4 символа)
        example: admin
        type: string
      password:
        description: Пароль для доступа к системе
        example: admin123
        type: string
    type: object
  dto.AdminAuthResponse:
    properties:
      token:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        type: string
    type: object
  dto.ErrorResponse:
    properties:
      error:
        type: string
    type: object
info:
  contact: {}
  description: API системы управления запасами еды.
  title: FoodStock API
  version: "1.0"
paths:
  /admin/auth:
    post:
      consumes:
      - application/json
      description: Проверяет логин/пароль и возвращает JWT токен
      parameters:
      - description: Данные для входа
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/dto.AdminAuthRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Токен успешно выдан
          schema:
            $ref: '#/definitions/dto.AdminAuthResponse'
        "400":
          description: Невалидный JSON
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "401":
          description: Неверный логин или пароль
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Авторизация администратора
      tags:
      - Auth
swagger: "2.0"
