name: Backend Quality Control

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.26.2'
          cache: true
          cache-dependency-path: backend/go.sum

      - name: Run golangci-lint
        run: go run github.com/golangci/golangci-lint/cmd/golangci-lint@latest run ./...
        working-directory: backend

  tests:
    name: Run tests
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.26.2'
          cache: true
          cache-dependency-path: backend/go.sum

      - name: Run Unit Tests
        working-directory: ./backend
        run: go test -v -short -coverprofile=unit.out -covermode=atomic ./internal/...

      - name: Run Integration Tests
        working-directory: ./backend
        run: go test -v -tags=integration -coverprofile=integration.out ./internal/adapter/...

      - name: Merge Coverage Profiles
        working-directory: ./backend
        run: |
          cat unit.out > coverage.txt
          grep -v "mode:" integration.out >> coverage.txt

      - name: Generate Full Coverage Report
        working-directory: ./backend
        run: |
          echo "### 📊 Полное покрытие всего проекта тестами" > report.md
          echo "\`\`\`text" >> report.md
          go tool cover -func=coverage.txt >> report.md
          echo "\`\`\`" >> report.md
            
      - name: Post Coverage Comment
        uses: marocchino/sticky-pull-request-comment@v3.0.4
        with:
          header: total-coverage
          path: backend/report.md
        if: github.event_name == 'pull_request'

      - name: Run E2E Tests
        working-directory: ./backend/tests/e2e
        run: go test -v -tags=e2e
